config/routes.rb
Rails.application.routes.draw do

  get 'admin/index'

  resources :categories do
    resources :proyects
  end

  resources :proyects do
    resources :pictures
  end
  
  devise_for :admins
  get 'home/index'

  root to:'admin#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :proyects, dependent: :destroy
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :proyect    

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/proyect.rb
class Proyect < ApplicationRecord
  belongs_to :category
  has_many :pictures, dependent: :destroy
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!
  def index
    @categories = Category.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected

  def after_sign_in_path_for(resource)
    admin_index_path
  end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path}
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_proyect, only: [:create, :edit, :index, :show, :new]
  before_action :set_picture, only: [:edit, :destroy, :update, :show]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = @proyect.pictures.build(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to proyect_pictures_path}
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to proyect_pictures_path(@picture.proyect) }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to proyect_pictures_path(@picture.proyect)}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    def set_proyect
      @proyect = Proyect.find(params[:proyect_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:avatar, :name, :proyect_id)
    end
end

app/controllers/proyects_controller.rb
class ProyectsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_category, only: [:create, :edit, :index, :new]
  before_action :set_proyect, only: [:edit, :destroy, :show, :update]

  # GET /proyects
  # GET /proyects.json
  def index
    @proyects = Proyect.all
  end

  # GET /proyects/1
  # GET /proyects/1.json
  def show
  end

  # GET /proyects/new
  def new
    @proyect = Proyect.new
  end

  # GET /proyects/1/edit
  def edit
  end

  # POST /proyects
  # POST /proyects.json
  def create
    @proyect = @category.proyects.build(proyect_params)

    respond_to do |format|
      if @proyect.save
        format.html { redirect_to category_proyects_path}
        format.json { render :show, status: :created, location: @proyect }
      else
        format.html { render :new }
        format.json { render json: @proyect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proyects/1
  # PATCH/PUT /proyects/1.json
  def update
    respond_to do |format|
      if @proyect.update(proyect_params)
        format.html { redirect_to category_proyects_path(@proyect.category) }
        format.json { render :show, status: :ok, location: @proyect }
      else
        format.html { render :edit }
        format.json { render json: @proyect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proyects/1
  # DELETE /proyects/1.json
  def destroy
    @proyect.destroy
    respond_to do |format|
      format.html { redirect_to category_proyects_url, notice: 'Proyect was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proyect
      @proyect = Proyect.find(params[:id])
    end

    def set_category
      @category = Category.find(params[:category_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proyect_params
      params.require(:proyect).permit(:name, :category_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/proyects_helper.rb
module ProyectsHelper
end

app/views/admin/index.html.haml
.row.justify-content-center
  .col-5.card.p-4.bc-card.text-center
    %h2.pb-4.font-color Admin Panel
    .row.p-4.justify-content-center
      .col-6.admin-border.rounded.py-2
        = fa_icon "list-ul", class: "admin-icon pb-2"
        %h3.font-color
          Quantity:
          = @categories.length
        = link_to 'Categories', categories_path, class: 'btn admin-button btn-block'

app/views/categories/_form.html.haml
-# = form_for @category do |f|
-#   - if @category.errors.any?
-#     #error_explanation
-#       %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
-#       %ul
-#         - @category.errors.full_messages.each do |message|
-#           %li= message

-#   .field
-#     = f.label :name
-#     = f.text_field :name
-#   .actions
-#     = f.submit 'Save'

= form_for @category do |f|
  .row
    .col-12.text-left
      .form-group
        = f.label 'Name:', class: "font-color"
        = f.text_field :name, class: 'form-control form-style', placeholder: 'Please enter a name'
    .col-12
      .actions.text-center
        = f.submit "Save", class: 'btn admin-button btn-block'

app/views/categories/edit.html.haml
-# %h1 Editing category

-# = render 'form'

-# = link_to 'Show', @category
-# \|
-# = link_to 'Back', categories_path

.row.justify-content-center
  .col-5.card.p-4.bc-card.text-center
    %h2.pb-2.font-color 
      Category:
      = @category.name
    .row.justify-content-start
      .col-2.ml-4
        = link_to categories_path do
          = fa_icon "arrow-circle-left", class: "fa-2x btn admin-button btn-block"
    .row.p-4.mt-3.justify-content-center
      .col-7
        = render 'form'

app/views/categories/index.html.haml
-# %h1 Listing categories

-# %table
-#   %thead
-#     %tr
-#       %th Name
-#       %th
-#       %th
-#       %th

-#   %tbody
-#     - @categories.each do |category|
-#       %tr
-#         %td= category.name
-#         %td= link_to 'Show', category
-#         %td= link_to 'Edit', edit_category_path(category)
-#         %td= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }

-# %br

-# = link_to 'New Category', new_category_path

.row.justify-content-center
  .col-5.card.p-4.bc-card.text-center
    %h2.pb-4.font-color Categories
    .row.justify-content-start
      .col-2.ml-4
        = link_to new_category_path do
          = fa_icon "plus-circle", class: "fa-2x btn admin-button btn-block"
      .col-2
        = link_to admin_index_path do
          = fa_icon "arrow-circle-left", class: "fa-2x btn admin-button btn-block"
    .row.p-4.mt-3.justify-content-center
      .col-12
        - if @categories.any?
          - @categories.each do |category|
            .row
              .col-6
                = link_to category_proyects_path(category), class: "font-color" do
                  = category.name
              .col-2
                = link_to edit_category_path(category) do
                  = fa_icon "pencil", class: "fa-lg btn admin-button"
              .col-2
                = link_to category, method: :delete do
                  = fa_icon "trash", class: "fa-lg btn admin-button"
            %hr.hr-style
        - else
          .row
            .col-12
              %h3.font-color
                There are no categories created
    

app/views/categories/new.html.haml
-# %h1 New category

-# = render 'form'

-# = link_to 'Back', categories_path

.row.justify-content-center
  .col-5.card.p-4.bc-card.text-center
    %h2.pb-2.font-color New Category
    .row.justify-content-start
      .col-2.ml-4
        = link_to categories_path do
          = fa_icon "arrow-circle-left", class: "fa-2x btn admin-button btn-block"
    .row.p-4.mt-3.justify-content-center
      .col-7
        = render 'form'

app/views/categories/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @category.name

= link_to 'Edit', edit_category_path(@category)
\|
= link_to 'Back', categories_path

app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.erb
= link_to 'Panel', proyects_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FerminFraguas
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container-fluid
      .row.pt-5
        .col-12
          = yield

app/views/pictures/_form.html.haml
-# = form_with(model: picture, local: true) do |form|
-#   - if picture.errors.any?
-#     #error_explanation
-#       %h2
-#         = pluralize(picture.errors.count, "error")
-#         prohibited this picture from being saved:
-#       %ul
-#         - picture.errors.full_messages.each do |message|
-#           %li= message
-#   .field
-#     = form.label :name
-#     = form.text_field :name, id: :picture_name
-#   .actions
-#     = form.submit

-# = form_for [:proyect, @picture] do |f|
-#   .form-group
-#     = f.label 'Avatar'
-#     = f.file_field :avatar, class: 'form-control'
-#   .form-group
-#     = f.label 'Nombre'
-#     = f.text_field :name, class: 'form-control', placeholder: 'Introduce un nombre'
-#   .actions.text-center
-#     = f.submit "Guardar", class: 'btn btn-success'

= form_for [:proyect, @picture] do |f|
  .row
    .col-12.text-left
      .form-group
        = f.label 'Avatar:', class: "font-color"
        = f.file_field :avatar, class: 'form-control form-style'
      .form-group
        = f.label 'Name:', class: "font-color"
        = f.text_field :name, class: 'form-control form-style', placeholder: 'Please enter a name'
    .col-12
      .actions.text-center
        = f.submit "Save", class: 'btn admin-button btn-block'

app/views/pictures/edit.html.haml
-# %h1 Editing Picture
-# = render 'form', picture: @picture
-# = link_to 'Show', @picture
-# |
-# = link_to 'Back', pictures_path

.row.justify-content-center
  .col-5.card.p-4.bc-card.text-center
    %h2.pb-2.font-color 
      Picture:
      = @picture.name
    %h3.pb-2.font-color
      Proyect:
      = @proyect.name
    .row.justify-content-start
      .col-2.ml-4
        = link_to proyect_pictures_path(@proyect) do
          = fa_icon "arrow-circle-left", class: "fa-2x btn admin-button btn-block"
    .row.p-4.mt-3.justify-content-center
      .col-9
        = render 'form'

app/views/pictures/index.html.haml
-# %p#notice= notice
-# %h1 Pictures
-# %table
-#   %thead
-#     %tr
-#       %th Name
-#       %th{:colspan => "3"}
-#   %tbody
-#     - @pictures.each do |picture|
-#       %tr
-#         %td= picture.name
-#         %td= link_to 'Show', picture
-#         %td= link_to 'Edit', edit_picture_path(picture)
-#         %td= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' }
-# %br/
-# = link_to 'New Picture', new_picture_path

-# %p#notice= notice
-# %h1 Pictures
-# %table
-#   %thead
-#     %tr
-#       %th Name
-#       %th{:colspan => "3"}
-#   %tbody
-#     - @proyect.pictures.each do |picture|
-#       %tr
-#         %td= picture.name
-#         %td= link_to 'Show', proyect_picture_path(@proyect, picture)
-#         %td= link_to 'Edit', edit_proyect_picture_path(@proyect, picture)
-#         %td= link_to 'Destroy', proyect_picture_path(@proyect, picture), method: :delete, data: { confirm: 'Are you sure?' }
-# %br/
-# = link_to 'New Picture', new_proyect_picture_path  
-# |
-# = link_to 'Back', proyect_path(@proyect)

.row.justify-content-center
  .col-5.card.p-4.bc-card.text-center
    %h2.pb-2.font-color Pictures
    %h3.pb-2.font-color
      Proyect:
      = @proyect.name
    %h4.pb-4.font-color
      Number of pictures:
      = @proyect.pictures.length
    .row.justify-content-start
      .col-2.ml-4
        = link_to new_proyect_picture_path do
          = fa_icon "plus-circle", class: "fa-2x btn admin-button btn-block"
      .col-2
        = link_to category_proyects_path(@proyect.category) do
          = fa_icon "arrow-circle-left", class: "fa-2x btn admin-button btn-block"
    .row.p-4.mt-3.justify-content-center
      .col-12
        - if @proyect.pictures.any?
          - @proyect.pictures.each do |picture|
            .row
              .col-6
                = link_to proyect_picture_path(@proyect, picture), class: "font-color" do
                  = picture.name
              .col-2
                = link_to edit_proyect_picture_path(@proyect, picture) do
                  = fa_icon "pencil", class: "fa-lg btn admin-button"
              .col-2
                = link_to proyect_picture_path(@proyect, picture), method: :delete do
                  = fa_icon "trash", class: "fa-lg btn admin-button"
            %hr.hr-style
        - else
          .row
            .col-12
              %h3.font-color
                There are no pictures created

app/views/pictures/new.html.haml
-# .col-12
-#   .row.justify-content-center
-#     .col-4
-#       .card
-#         %h1 New Picture
-#         = render 'form'
-#         = link_to 'Back', proyect_pictures_path

.row.justify-content-center
  .col-5.card.p-4.bc-card.text-center
    %h2.pb-2.font-color New Picture
    %h3.pb-2.font-color
      Proyect:
      = @proyect.name
    .row.justify-content-start
      .col-2.ml-4
        = link_to proyect_pictures_path(@proyect) do
          = fa_icon "arrow-circle-left", class: "fa-2x btn admin-button btn-block"
    .row.p-4.mt-3.justify-content-center
      .col-9
        = render 'form'

app/views/pictures/show.html.haml
%p
  %strong Image:
= image_tag @picture.avatar.url(:medium)
%p
  %strong Name:
  = @picture.name
%p
  %strong File_name:
  = @picture.avatar_file_name
%br
= link_to 'Edit', edit_proyect_picture_path(@proyect, @picture)
|
= link_to 'Back', proyect_pictures_path

app/views/proyects/_form.html.haml
-# = form_with(model: proyect, local: true) do |form|
-#   - if proyect.errors.any?
-#     #error_explanation
-#       %h2
-#         = pluralize(proyect.errors.count, "error")
-#         prohibited this proyect from being saved:
-#       %ul
-#         - proyect.errors.full_messages.each do |message|
-#           %li= message
-#   .field
-#     = form.label :name
-#     = form.text_field :name, id: :proyect_name
-#   .actions
-#     = form.submit

-# = form_for [:category, @proyect] do |f|
-#   .form-group
-#     = f.label 'Nombre'
-#     = f.text_field :name, class: 'form-control', placeholder: 'Introduce un nombre'
-#   .actions.text-center
-#     = f.submit "Guardar", class: 'btn btn-success'

= form_for [:category, @proyect] do |f|
  .row
    .col-12.text-left
      .form-group
        = f.label 'Name:', class: "font-color"
        = f.text_field :name, class: 'form-control form-style', placeholder: 'Please enter a name'
    .col-12
      .actions.text-center
        = f.submit "Save", class: 'btn admin-button btn-block'

app/views/proyects/edit.html.haml
-# %h1 Editing Proyect
-# = render 'form', proyect: @proyect
-# = link_to 'Show', @proyect
-# |
-# = link_to 'Back', proyects_path

.row.justify-content-center
  .col-5.card.p-4.bc-card.text-center
    %h2.pb-2.font-color 
      Proyect:
      = @proyect.name
    %h3.pb-2.font-color
      Category:
      = @category.name
    .row.justify-content-start
      .col-2.ml-4
        = link_to category_proyects_path(@category) do
          = fa_icon "arrow-circle-left", class: "fa-2x btn admin-button btn-block"
    .row.p-4.mt-3.justify-content-center
      .col-7
        = render 'form'

app/views/proyects/index.html.haml
-# %p#notice= notice
-# %h1 Proyects
-# %table
-#   %thead
-#     %tr
-#       %th Name
-#       %th{:colspan => "4"}
-#   %tbody
-#     - @proyects.each do |proyect|
-#       %tr
-#         %td= proyect.name
-#         %td= link_to 'Pictures', proyect_pictures_path(proyect)
-#         %td= link_to 'Show', proyect
-#         %td= link_to 'Edit', edit_proyect_path(proyect)
-#         %td= link_to 'Destroy', proyect, method: :delete, data: { confirm: 'Are you sure?' }
-# %br/
-# = link_to 'New Proyect', new_category_proyect_path

.row.justify-content-center
  .col-5.card.p-4.bc-card.text-center
    %h2.pb-2.font-color Proyects
    %h3.pb-2.font-color
      Category:
      = @category.name
    %h4.pb-4.font-color
      Number of proyects:
      = @category.proyects.length
    .row.justify-content-start
      .col-2.ml-4
        = link_to new_category_proyect_path do
          = fa_icon "plus-circle", class: "fa-2x btn admin-button btn-block"
      .col-2
        = link_to categories_path(@category) do
          = fa_icon "arrow-circle-left", class: "fa-2x btn admin-button btn-block"
    .row.p-4.mt-3.justify-content-center
      .col-12
        - if @category.proyects.any?
          - @category.proyects.each do |proyect|
            .row
              .col-6
                = link_to proyect_pictures_path(proyect), class: "font-color" do
                  = proyect.name
              .col-2
                = link_to edit_category_proyect_path(@category, proyect) do
                  = fa_icon "pencil", class: "fa-lg btn admin-button"
              .col-2
                = link_to category_proyect_path(@category, proyect), method: :delete do
                  = fa_icon "trash", class: "fa-lg btn admin-button"
            %hr.hr-style
        - else
          .row
            .col-12
              %h3.font-color
                There are no proyects created

app/views/proyects/new.html.haml
-# %h1 New Proyect
-# = render 'form', proyect: @proyect
-# = link_to 'Back', proyects_path

.row.justify-content-center
  .col-5.card.p-4.bc-card.text-center
    %h2.pb-2.font-color New Proyect
    %h3.pb-2.font-color
      Category:
      = @category.name
    .row.justify-content-start
      .col-2.ml-4
        = link_to category_proyects_path(@category) do
          = fa_icon "arrow-circle-left", class: "fa-2x btn admin-button btn-block"
    .row.p-4.mt-3.justify-content-center
      .col-7
        = render 'form'

app/views/proyects/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @proyect.name
- @proyect.pictures.each do |picture|
  = image_tag picture.avatar.url(:medium)
%br
= link_to 'Pictures', proyect_pictures_path(@proyect)
|
= link_to 'Edit', edit_proyect_path(@proyect)
|
= link_to 'Back', proyects_path